# Generated by Django 6.1.1 on 2026-09-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtask',
            new_name='Subtasks',
        ),
    ]
